GET http://localhost:5000/api/user/eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NDAwZDg2ZTI5MmIwNmZmNTFkNWM0YjQiLCJlbWFpbCI6InBvdHRlckBob2d3YXJ0cy5jb20iLCJpYXQiOjE2NzgxMjM5OTMsImV4cCI6MTY3ODEyNzU5M30.ujT7LRLJycrm1iMISnRiqOBOUw2A9lZDr-amDiDdVC8 HTTP/1.1